header: |
  made by xPand
     _____                   _         ______  _  _
    |  __ \                 | |       |  ____|| |(_)
    | |__) |__ _  _ __    __| |  __ _ | |__   | | _ __  __
    |  ___// _  ||  _ \  / _  | / _  ||  __|  | || |\ \/ /
    | |   ( (_| || | | || (_| |( (_| || |     | || | )  (
    |_|    \__,_||_| |_| \__,_| \__,_||_|     |_||_|/_/\_\

paths:
  - dev-ops/common/actions

const:
  APP_NAME: "PandaFlix"
  APP_URL: "http://localhost"
  APP_TIMEZONE: "Europe/Berlin"

  LOG_CHANNEL: "stack"

  DB_CONNECTION: "mysql"
  DB_HOST: "127.0.0.1"
  DB_PORT: "3306"
  DB_DATABASE: "PandaFlix"
  DB_USERNAME: "root"
  DB_PASSWORD: ""

  BROADCAST_DRIVER: "log"
  CACHE_DRIVER: "file"
  QUEUE_CONNECTION: "sync"
  SESSION_DRIVER: "database"
  SESSION_LIFETIME: "120"

  REDIS_HOST: "127.0.0.1"
  REDIS_PASSWORD: "null"
  REDIS_PORT: "6379"

  MAIL_DRIVER: "smtp"
  MAIL_HOST: "smtp.mailtrap.io"
  MAIL_PORT: "2525"
  MAIL_USERNAME: "null"
  MAIL_PASSWORD: "null"
  MAIL_ENCRYPTION: "null"

  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_DEFAULT_REGION: "eu-central-1"
  AWS_BUCKET:

  PUSHER_APP_ID:
  PUSHER_APP_KEY:
  PUSHER_APP_SECRET:
  PUSHER_APP_CLUSTER: "eu"

environments:
  pandaflix:
    templates:
      - source: "dev-ops/pandaflix/templates/.env.dist"
        destination: ".env"
    paths:
      - "dev-ops/pandaflix/actions"

  dev:
    templates:
      - source: "dev-ops/dev/templates/.env.dist"
        destination: ".env"
    paths:
      - "dev-ops/dev/actions"

  github:
    templates:
      - source: "dev-ops/dev/templates/.env.dist"
        destination: ".env"
    paths:
      - "dev-ops/workflows/actions"
