name: Main workflow

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  laravel-tests:
    name: Run Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Give access rights.
      run: chmod +x ./psh.phar
    - name: Run init script.
      run: ./psh.phar github:init
    - name: Execute tests (Unit and Feature tests) via PHPUnit.
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: app/Components/Common/Database/database.sqlite
      run: ./psh.phar github:unit
